// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import TurboModalController from "./turbo_modal_controller"
application.register("turbo-modal", TurboModalController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import MapController from "./map_controller"
application.register("map", MapController)
